version: '3'
services:
  php-apache:
    image: php:apache
    ports:
      - 80:80
    volumes:
      - "./:/var/www/html" # sync the current dir on the local machine to the dir of the container
    command: >
      /bin/bash -c "
        docker-php-ext-install mysqli &&
        apache2-foreground
      "
    depends_on:
      - db-mysql

  db-mysql: 
    image: mysql:latest
    environment: # login and passwd for db
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # save db when the container is closed
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db-mysql
      - PMA_PORT=3306
    depends_on:
      - db-mysql